name: Vercel Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: './'
        env:
          # Optional: set these as repository secrets if you want to target a specific
          # Vercel project/org. The action will attempt to auto-detect the project
          # when these aren't provided.
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Notes:
# 1) Add a repository secret named VERCEL_TOKEN (Personal Token from Vercel) in
#    Settings → Secrets → Actions before the workflow can deploy.
# 2) If you already have VERCEL_ORG_ID and VERCEL_PROJECT_ID values, add them as
#    secrets too to avoid auto-detection issues.